image: gitlab.os.dcso.net:4567/dev/docker/golang:1.20-bullseye
stages:
  - build
  - verify
  - style
  - package

variables:
  GONOSUMDB: gitlab.os.dcso.net
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/release/${CI_COMMIT_TAG}"

go_build:
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/mini-syslog-receiver-darwin-amd64
      - $CI_PROJECT_DIR/mini-syslog-receiver-darwin-arm64
      - $CI_PROJECT_DIR/mini-syslog-receiver-windows-amd64
      - $CI_PROJECT_DIR/mini-syslog-receiver-windows-i386
      - $CI_PROJECT_DIR/mini-syslog-receiver-linux-amd64
      - $CI_PROJECT_DIR/mini-syslog-receiver-linux-i386
  script:
    - go get -a -t -v -d  $(go list ./\...)
    - GOOS=darwin GOARCH=amd64 go build -v -o $CI_PROJECT_DIR/mini-syslog-receiver-darwin-amd64
    - GOOS=darwin GOARCH=arm64 go build -v -o $CI_PROJECT_DIR/mini-syslog-receiver-darwin-arm64
    - GOOS=windows GOARCH=amd64 go build -v -o $CI_PROJECT_DIR/mini-syslog-receiver-windows-amd64
    - GOOS=windows GOARCH=386 go build -v -o $CI_PROJECT_DIR/mini-syslog-receiver-windows-i386
    - GOOS=linux GOARCH=amd64 go build -v -o $CI_PROJECT_DIR/mini-syslog-receiver-linux-amd64
    - GOOS=linux GOARCH=386 go build -v -o $CI_PROJECT_DIR/mini-syslog-receiver-linux-i386
  tags:
        - dev

go_test:
    stage: verify
    script:
        - go test -v -cover ./...
    tags:
        - dev

go_vet:
    stage: verify
    script:
        - go vet $(go list ./... | grep -v "vendor")
    tags:
      - dev

staticcheck:
    stage: verify
    script:
        - go install honnef.co/go/tools/cmd/staticcheck@latest
        - staticcheck $(go list ./... | grep -v "vendor")
    tags:
        - dev

golint:
    stage: style
    script:
        - cd $PROJPATH
        - go install github.com/mgechev/revive@latest
        - revive ./...
    allow_failure: true
    tags:
        - dev

upload:
  stage: package
  needs:
    - job: go_build
      artifacts: true
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file mini-syslog-receiver-darwin-amd64 \
        ${PACKAGE_REGISTRY_URL}/mini-syslog-receiver-${CI_COMMIT_TAG}-darwin-amd64
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file mini-syslog-receiver-darwin-arm64 \
        ${PACKAGE_REGISTRY_URL}/mini-syslog-receiver-${CI_COMMIT_TAG}-darwin-arm64
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file mini-syslog-receiver-windows-amd64 \
        ${PACKAGE_REGISTRY_URL}/mini-syslog-receiver-${CI_COMMIT_TAG}-windows-amd64.exe
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file mini-syslog-receiver-windows-i386 \
        ${PACKAGE_REGISTRY_URL}/mini-syslog-receiver-${CI_COMMIT_TAG}-windows-i386.exe
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file mini-syslog-receiver-linux-amd64 \
        ${PACKAGE_REGISTRY_URL}/mini-syslog-receiver-${CI_COMMIT_TAG}-linux-amd64
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file mini-syslog-receiver-linux-i386 \
        ${PACKAGE_REGISTRY_URL}/mini-syslog-receiver-${CI_COMMIT_TAG}-linux-i386
  tags:
    - dev
