name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch}}
    strategy:
      matrix:
        arch:
          - 386
          - amd64
          - arm64
        os:
          - darwin
          - windows
          - linux
        exclude:
          - os: darwin
            arch: 386
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up user
        run: |
             useradd -m -g users testuser
             chown -R testuser:users .
      - name: Build for ${{ matrix.arch }} ${{ matrix.os }}
        run: |
             su -c "GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o binary-${{ matrix.os }}-${{ matrix.arch }}" testuser
