name: Build and test

on:
  - push
  - pull_request

jobs:
  linux:
    name: Build ${{ matrix.os }} ${{ matrix.arch}}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        arch:
          - i386
          - amd64
          - arm64
        os:
          - darwin
          - windows
          - linux
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up user
        run: |
             useradd -m -g users testuser
             chown -R testuser:users .
      - name: Build for ${{ matrix.arch }} ${{ matrix.os }}
        run: |
             su -c "GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o binary-${{ matrix.os }}-${{ matrix.arch }}" testuser
